### ISSUE TITLE
Вопрос 1

### ISSUE THREAD

**Issue by ASTeterin** [rrenatars/php#4]
Что будет, если не указать необязательный параметр?
https://github.com/rrenatars/php/blob/6414185bc92ac58fe8ae8a5c41fe455eb0ffa8dc/lws/lw4/task2/user.php#L48

**Comment by rrenatars** [comment]
> Что будет, если не указать необязательный параметр?
> 
> https://github.com/rrenatars/php/blob/6414185bc92ac58fe8ae8a5c41fe455eb0ffa8dc/lws/lw4/task2/user.php#L48

Если не указать необязательный параметр, то будет пустое значение. С этим что-то не так?

**Comment by ASTeterin** [comment]
Ошибка не будет падать, что значение по ключу 'middle_name' отсутствует в $_POST?

**Comment by rrenatars** [comment]
Не падает
![image](https://user-images.githubusercontent.com/124866571/234103919-90ee1241-8035-4d54-8ca1-8782dc8b7eb9.png)
